import React, { useState } from 'react';
import { CampaignRoom, CharacterSheet } from '../types/rpg';
import { sound } from '../utils/audio';
import { generateRandomRoomCode, normalizeRoomCode } from '../utils/roomCode';
import { campaignService } from '../services/campaignService';
import {
  X,
  Plus,
  Crown,
  User,
  KeyRound,
  CheckCircle2,
  Trash2,
  LogIn,
  Dice5,
  RotateCcw,
  Globe2,
  Search,
  Loader2,
  Share2,
  Check,
} from 'lucide-react';

interface LobbyModalProps {
  isOpen: boolean;
  onClose: () => void;
  availableCampaigns: CampaignRoom[];
  currentCampaignCode: string;
  onSelectCampaign: (code: string) => void;
  onCreateCampaign: (name: string, gmName: string, description: string, customCode?: string) => Promise<CampaignRoom> | CampaignRoom;
  onCreateCharacter: (campaignCode: string, char: CharacterSheet) => void;
  onDeleteCampaign?: (code: string) => void;
}

export const LobbyModal: React.FC<LobbyModalProps> = ({
  isOpen,
  onClose,
  availableCampaigns,
  currentCampaignCode,
  onSelectCampaign,
  onCreateCampaign,
  onCreateCharacter,
  onDeleteCampaign,
}) => {
  const [mode, setMode] = useState<'join' | 'create_campaign' | 'create_character'>('join');

  // Join State
  const [joinCodeInput, setJoinCodeInput] = useState('');
  const [joinError, setJoinError] = useState<string | null>(null);
  const [isSearchingOnline, setIsSearchingOnline] = useState(false);
  const [onlineRoomFound, setOnlineRoomFound] = useState<CampaignRoom | null>(null);

  // Create Campaign State: completely random code generated by default
  const [campName, setCampName] = useState('');
  const [gmName, setGmName] = useState('');
  const [randomCode, setRandomCode] = useState<string>(() => generateRandomRoomCode());
  const [isCustomCode, setIsCustomCode] = useState(false);
  const [customCode, setCustomCode] = useState('');
  const [campDesc, setCampDesc] = useState('');
  const [copiedCode, setCopiedCode] = useState<string | null>(null);

  // Create Character State
  const [charName, setCharName] = useState('');
  const [charTitle, setCharTitle] = useState('Aventureiro');
  const [charClass, setCharClass] = useState('Guerreiro Rúnico');
  const [charRace, setCharRace] = useState('Humano');
  const [selectedAvatar, setSelectedAvatar] = useState(
    'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80'
  );

  if (!isOpen) return null;

  const handleRegenerateRandomCode = () => {
    sound.playCoinClink('PRT');
    setRandomCode(generateRandomRoomCode());
  };

  const handleSearchRoom = async (codeToSearch: string) => {
    const clean = normalizeRoomCode(codeToSearch);
    if (!clean) return;

    setIsSearchingOnline(true);
    setJoinError(null);
    setOnlineRoomFound(null);

    const result = await campaignService.checkRoomExists(clean);
    setIsSearchingOnline(false);

    if (result.exists && result.campaign) {
      setOnlineRoomFound(result.campaign);
    } else {
      setJoinError(`Nenhuma sala online encontrada com o código "${clean}".`);
    }
  };

  const handleJoinByCode = async (e: React.FormEvent) => {
    e.preventDefault();
    setJoinError(null);
    const code = normalizeRoomCode(joinCodeInput);
    if (!code) return;

    setIsSearchingOnline(true);
    const result = await campaignService.checkRoomExists(code);
    setIsSearchingOnline(false);

    if (!result.exists || !result.campaign) {
      setJoinError(`Nenhuma sala online encontrada com o código "${code}".`);
      return;
    }

    sound.playSuccessFanfare();
    onSelectCampaign(code);
    onClose();
  };

  const handleCreateCampaignSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!campName.trim()) return;

    const finalCode = isCustomCode && customCode.trim()
      ? normalizeRoomCode(customCode)
      : randomCode;

    const newCamp = await onCreateCampaign(
      campName.trim(),
      gmName.trim() || 'Mestre do Jogo',
      campDesc.trim(),
      finalCode
    );

    sound.playSuccessFanfare();
    onSelectCampaign(newCamp.code);
    onClose();
  };

  const handleCreateCharacterSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!charName.trim()) return;

    const newChar: CharacterSheet = {
      id: 'char-' + Date.now() + '-' + Math.floor(Math.random() * 1000),
      campaignCode: currentCampaignCode,
      name: charName.trim(),
      title: charTitle.trim(),
      characterClass: charClass.trim(),
      race: charRace.trim(),
      level: 1,
      experience: 0,
      starsLevel: 1,
      avatarUrl: selectedAvatar,
      hp: { current: 25, max: 25 },
      mana: { current: 20, max: 20 },
      stamina: { current: 15, max: 15 },
      armorClass: 14,
      speed: '9m',
      initiative: 2,
      attributes: {
        FOR: 14,
        DES: 14,
        CON: 13,
        INT: 12,
        SAB: 10,
        CAR: 12,
      },
      traits: [
        { label: 'Percepção', value: '+2' },
        { label: 'Atletismo', value: '+3' },
        { label: 'Iniciativa', value: '+2' },
        { label: 'Vigor', value: '+1' },
        { label: 'Vontade', value: '+0' },
        { label: 'Visão', value: 'Normal' },
      ],
      skillsList: ['Ataque Básico', 'Defesa Rúnica'],
      abilities: [],
      inventory: [
        {
          id: 'inv-' + Date.now(),
          name: 'Espada de Ferro Nobre',
          quantity: 1,
          category: 'arma',
          description: 'Arma inicial.',
          valueAmount: 5,
          valueCurrency: 'BRZ',
        },
      ],
      wallet: {
        BRZ: 50,
        PRT: 10,
        ORO: 2,
        PLN: 0,
        CYB: 0,
      },
      notes: 'Personagem novo ingressado na sala online.',
      isMaster: false,
      isOnline: true,
      lastActive: Date.now(),
    };

    onCreateCharacter(currentCampaignCode, newChar);
    sound.playSuccessFanfare();
    onClose();
  };

  const AVATARS = [
    'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1563089145-599997674d42?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="relative w-full max-w-lg rounded-xl border border-purple-900/70 bg-[#0e0a1a] p-5 shadow-2xl overflow-hidden max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-purple-900/40">
          <div className="flex items-center gap-2">
            <Globe2 className="w-4 h-4 text-emerald-400" />
            <span className="text-sm font-cinzel font-bold text-zinc-100">
              Gerenciador de Salas Online
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-md text-zinc-400 hover:text-zinc-100 hover:bg-zinc-800/60 transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="grid grid-cols-3 gap-1.5 p-1 bg-zinc-950/80 rounded-lg border border-purple-900/40 my-3">
          <button
            type="button"
            onClick={() => setMode('join')}
            className={`py-1.5 rounded-md text-xs font-cinzel font-semibold flex items-center justify-center gap-1.5 transition ${
              mode === 'join'
                ? 'bg-amber-500 text-zinc-950 font-bold shadow-sm'
                : 'text-zinc-400 hover:text-amber-200'
            }`}
          >
            <LogIn className="w-3.5 h-3.5" />
            Entrar em Sala
          </button>

          <button
            type="button"
            onClick={() => {
              setMode('create_campaign');
              if (!randomCode) handleRegenerateRandomCode();
            }}
            className={`py-1.5 rounded-md text-xs font-cinzel font-semibold flex items-center justify-center gap-1.5 transition ${
              mode === 'create_campaign'
                ? 'bg-amber-500 text-zinc-950 font-bold shadow-sm'
                : 'text-zinc-400 hover:text-amber-200'
            }`}
          >
            <Crown className="w-3.5 h-3.5" />
            Criar Sala
          </button>

          <button
            type="button"
            onClick={() => setMode('create_character')}
            className={`py-1.5 rounded-md text-xs font-cinzel font-semibold flex items-center justify-center gap-1.5 transition ${
              mode === 'create_character'
                ? 'bg-amber-500 text-zinc-950 font-bold shadow-sm'
                : 'text-zinc-400 hover:text-amber-200'
            }`}
          >
            <User className="w-3.5 h-3.5" />
            Nova Ficha
          </button>
        </div>

        {/* Body content */}
        <div className="flex-1 overflow-y-auto pr-1">
          {/* MODE 1: ENTRAR EM SALA COM CÓDIGO */}
          {mode === 'join' && (
            <div className="space-y-4">
              <form onSubmit={handleJoinByCode} className="space-y-3">
                <div>
                  <label className="block text-xs text-zinc-400 mb-1 font-medium">
                    Código Aleatório da Sala *
                  </label>
                  <div className="flex gap-2">
                    <div className="relative flex-1">
                      <KeyRound className="w-4 h-4 text-amber-400 absolute left-3 top-1/2 -translate-y-1/2" />
                      <input
                        type="text"
                        placeholder="Ex: 9M2K4W ou cole o link"
                        value={joinCodeInput}
                        onChange={(e) => {
                          let val = e.target.value;
                          if (val.includes('room=')) {
                            const match = val.match(/room=([A-Za-z0-9_-]+)/);
                            if (match) val = match[1];
                          }
                          setJoinCodeInput(val.toUpperCase());
                          setOnlineRoomFound(null);
                          setJoinError(null);
                        }}
                        className="w-full bg-zinc-950 border border-purple-900/60 rounded-md pl-9 pr-3 py-2 text-sm font-mono text-amber-300 uppercase focus:outline-none focus:border-amber-500"
                      />
                    </div>
                    <button
                      type="button"
                      onClick={() => handleSearchRoom(joinCodeInput)}
                      disabled={!joinCodeInput.trim() || isSearchingOnline}
                      className="px-3 py-2 bg-purple-950 hover:bg-purple-900 border border-purple-800 text-purple-200 text-xs font-medium rounded-md transition flex items-center gap-1"
                    >
                      {isSearchingOnline ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Search className="w-3.5 h-3.5" />}
                    </button>
                    <button
                      type="submit"
                      className="px-4 py-2 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 text-zinc-950 font-bold text-xs rounded-md shadow-sm transition"
                    >
                      Entrar
                    </button>
                  </div>
                </div>

                {onlineRoomFound && (
                  <div className="p-3 rounded-lg border border-emerald-500/50 bg-emerald-950/30 text-xs">
                    <div className="flex items-center justify-between font-bold text-emerald-200">
                      <span>{onlineRoomFound.name}</span>
                      <span className="font-mono text-amber-300">{onlineRoomFound.code}</span>
                    </div>
                    <div className="text-zinc-400 mt-1">
                      Mestre: {onlineRoomFound.gmName} • {onlineRoomFound.players.length} Jogadores
                    </div>
                  </div>
                )}

                {joinError && (
                  <div className="p-2.5 rounded-md bg-red-950/40 border border-red-900/60 text-red-300 text-xs">
                    {joinError}
                  </div>
                )}
              </form>

              {/* Salas Disponíveis */}
              <div className="pt-3 border-t border-purple-900/40">
                <span className="text-xs text-zinc-400 font-medium block mb-2">
                  Salas Ativas no Servidor:
                </span>
                <div className="space-y-1.5 max-h-48 overflow-y-auto pr-1">
                  {availableCampaigns.length === 0 ? (
                    <div className="text-center py-4 text-xs text-zinc-500">
                      Nenhuma sala online encontrada.
                    </div>
                  ) : (
                    availableCampaigns.map((camp) => (
                      <div
                        key={camp.code}
                        className={`p-2.5 rounded-lg border flex items-center justify-between transition ${
                          camp.code === currentCampaignCode
                            ? 'border-amber-500/60 bg-purple-950/40'
                            : 'border-zinc-800 bg-zinc-950/60 hover:border-purple-800'
                        }`}
                      >
                        <div
                          onClick={() => {
                            onSelectCampaign(camp.code);
                            onClose();
                          }}
                          className="cursor-pointer flex-1"
                        >
                          <div className="flex items-center gap-2">
                            <h4 className="font-semibold text-zinc-200 text-xs">
                              {camp.name}
                            </h4>
                            <span className="px-1.5 py-0.2 rounded bg-zinc-800 text-amber-300 font-mono text-[10px]">
                              {camp.code}
                            </span>
                          </div>
                          <span className="text-[11px] text-zinc-400">
                            Mestre: {camp.gmName} • {camp.players.length} Fichas
                          </span>
                        </div>

                        <div className="flex items-center gap-2">
                          {camp.code === currentCampaignCode ? (
                            <span className="text-[11px] text-emerald-400 font-medium flex items-center gap-1">
                              <CheckCircle2 className="w-3.5 h-3.5" /> Atual
                            </span>
                          ) : (
                            <button
                              onClick={() => {
                                onSelectCampaign(camp.code);
                                onClose();
                              }}
                              className="text-xs text-amber-400 hover:text-amber-300 font-bold"
                            >
                              Entrar ➔
                            </button>
                          )}

                          {onDeleteCampaign && (
                            <button
                              onClick={(e) => {
                                e.stopPropagation();
                                if (confirm(`Excluir sala "${camp.name}" (${camp.code})?`)) {
                                  onDeleteCampaign(camp.code);
                                }
                              }}
                              className="p-1 text-zinc-500 hover:text-red-400 rounded transition"
                              title="Excluir Sala"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          )}
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          )}

          {/* MODE 2: CRIAR NOVA CAMPANHA */}
          {mode === 'create_campaign' && (
            <form onSubmit={handleCreateCampaignSubmit} className="space-y-3.5 text-xs">
              {/* Random room code highlight */}
              <div className="p-3 rounded-lg border border-amber-500/40 bg-amber-950/20">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[11px] font-cinzel font-bold text-amber-300 uppercase">
                    Código Aleatório de Conexão Online:
                  </span>
                  <button
                    type="button"
                    onClick={handleRegenerateRandomCode}
                    className="text-[10px] text-amber-400 hover:text-amber-200 flex items-center gap-1"
                  >
                    <Dice5 className="w-3 h-3" />
                    Sortear Outro
                  </button>
                </div>
                <div className="flex items-center justify-between bg-zinc-950 px-3 py-2 rounded border border-zinc-800 font-mono text-sm font-bold text-amber-300">
                  <span>{randomCode}</span>
                  <span className="text-[10px] font-sans text-zinc-500">100% Aleatório</span>
                </div>
              </div>

              <div>
                <label className="block text-zinc-400 font-medium mb-1">
                  Nome da Campanha *
                </label>
                <input
                  type="text"
                  required
                  placeholder="Ex: Nexaria — O Legado do Abismo"
                  value={campName}
                  onChange={(e) => setCampName(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-3 py-1.5 text-zinc-100 focus:outline-none focus:border-amber-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-zinc-400 font-medium mb-1">
                    Mestre (GM)
                  </label>
                  <input
                    type="text"
                    placeholder="Ex: Mestre Vaelor"
                    value={gmName}
                    onChange={(e) => setGmName(e.target.value)}
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-3 py-1.5 text-zinc-100 focus:outline-none focus:border-amber-500"
                  />
                </div>

                <div>
                  <label className="block text-zinc-400 font-medium mb-1">
                    Código Customizado (Opcional)
                  </label>
                  <input
                    type="text"
                    placeholder="Deixe vazio para usar o aleatório"
                    value={customCode}
                    onChange={(e) => {
                      setCustomCode(e.target.value.toUpperCase());
                      setIsCustomCode(!!e.target.value.trim());
                    }}
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-3 py-1.5 font-mono text-amber-300 uppercase focus:outline-none focus:border-amber-500"
                  />
                </div>
              </div>

              <div>
                <label className="block text-zinc-400 font-medium mb-1">
                  Descrição
                </label>
                <textarea
                  rows={2}
                  placeholder="Contexto da campanha e regras monetárias..."
                  value={campDesc}
                  onChange={(e) => setCampDesc(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-3 py-1.5 text-zinc-100 focus:outline-none focus:border-amber-500"
                />
              </div>

              <button
                type="submit"
                className="w-full py-2 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 text-zinc-950 font-cinzel font-bold text-xs rounded-md shadow-sm flex items-center justify-center gap-2 transition mt-2"
              >
                <Crown className="w-3.5 h-3.5" />
                Criar Sala Online com Código Aleatório
              </button>
            </form>
          )}

          {/* MODE 3: CRIAR FICHA DE PERSONAGEM */}
          {mode === 'create_character' && (
            <form onSubmit={handleCreateCharacterSubmit} className="space-y-3.5 text-xs">
              <div>
                <label className="block text-zinc-400 font-medium mb-1">
                  Nome do Personagem *
                </label>
                <input
                  type="text"
                  required
                  placeholder="Ex: Kaelen das Sombras"
                  value={charName}
                  onChange={(e) => setCharName(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-3 py-1.5 text-zinc-100 focus:outline-none focus:border-amber-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-zinc-400 font-medium mb-1">
                    Título / Conceito
                  </label>
                  <input
                    type="text"
                    placeholder="Ex: Mercenário"
                    value={charTitle}
                    onChange={(e) => setCharTitle(e.target.value)}
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-3 py-1.5 text-zinc-100 focus:outline-none focus:border-amber-500"
                  />
                </div>

                <div>
                  <label className="block text-zinc-400 font-medium mb-1">
                    Classe
                  </label>
                  <select
                    value={charClass}
                    onChange={(e) => setCharClass(e.target.value)}
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-3 py-1.5 text-zinc-100 focus:outline-none focus:border-amber-500"
                  >
                    <option value="Guerreiro Rúnico">Guerreiro Rúnico</option>
                    <option value="Tecnomago do Abismo">Tecnomago do Abismo</option>
                    <option value="Ladino das Sombras">Ladino das Sombras</option>
                    <option value="Paladino de Platina">Paladino de Platina</option>
                    <option value="Clérigo Astral">Clérigo Astral</option>
                    <option value="Bárbaro da Fenda">Bárbaro da Fenda</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-zinc-400 font-medium mb-1">
                  Avatar / Retrato
                </label>
                <div className="flex items-center gap-2">
                  {AVATARS.map((url, i) => (
                    <img
                      key={i}
                      src={url}
                      alt="Preset"
                      onClick={() => setSelectedAvatar(url)}
                      className={`w-10 h-10 rounded-md object-cover cursor-pointer border transition ${
                        selectedAvatar === url
                          ? 'border-amber-400 scale-105'
                          : 'border-zinc-800 opacity-60 hover:opacity-100'
                      }`}
                    />
                  ))}
                </div>
              </div>

              <div className="p-2.5 rounded bg-zinc-950 border border-purple-900/40 text-[11px] text-zinc-400">
                A bolsa inicial oficial será preenchida com <strong className="text-amber-300">50 BRZ, 10 PRT, 2 ORO</strong>.
              </div>

              <button
                type="submit"
                className="w-full py-2 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 text-zinc-950 font-cinzel font-bold text-xs rounded-md shadow-sm flex items-center justify-center gap-2 transition mt-2"
              >
                <User className="w-3.5 h-3.5" />
                Criar Ficha Online e Ingressar
              </button>
            </form>
          )}
        </div>
      </div>
    </div>
  );
};
