import React, { useState, useEffect } from 'react';
import { CampaignRoom, CharacterSheet, PLAYABLE_RACES, PLAYABLE_CLASSES } from '../types/rpg';
import { ORIGIN_REGIONS, getRegionById } from '../data/eldriaWorldMap';
import { CoinVisual } from './CoinVisual';
import { sound } from '../utils/audio';
import { generateRandomRoomCode, normalizeRoomCode } from '../utils/roomCode';
import { campaignService } from '../services/campaignService';
import {
  LogIn,
  PlusCircle,
  UserPlus,
  Trash2,
  Copy,
  Check,
  CheckCircle2,
  KeyRound,
  ArrowRight,
  RotateCcw,
  Sparkles,
  BookOpen,
  Dice5,
  Share2,
  Globe2,
  Search,
  Loader2,
  Users,
} from 'lucide-react';

interface RoomLobbyViewProps {
  availableCampaigns: CampaignRoom[];
  currentCampaignCode: string;
  onSelectCampaign: (code: string) => void;
  onCreateCampaign: (name: string, gmName: string, description: string, customCode?: string) => Promise<CampaignRoom> | CampaignRoom;
  onCreateCharacter: (campaignCode: string, char: CharacterSheet) => void;
  onDeleteCampaign: (code: string) => void;
  onResetAllData: () => void;
  onCloseLobbyView?: () => void;
  onOpenTutorial?: () => void;
}

export const RoomLobbyView: React.FC<RoomLobbyViewProps> = ({
  availableCampaigns,
  currentCampaignCode,
  onSelectCampaign,
  onCreateCampaign,
  onCreateCharacter,
  onDeleteCampaign,
  onResetAllData,
  onCloseLobbyView,
  onOpenTutorial,
}) => {
  const [activeTab, setActiveTab] = useState<'join' | 'create_room' | 'create_character' | 'manage_rooms'>('join');

  // Join Room State
  const [joinCode, setJoinCode] = useState('');
  const [joinError, setJoinError] = useState<string | null>(null);
  const [isSearchingOnline, setIsSearchingOnline] = useState(false);
  const [onlineRoomFound, setOnlineRoomFound] = useState<CampaignRoom | null>(null);

  // Create Room State: completely random code generated by default
  const [roomName, setRoomName] = useState('');
  const [gmName, setGmName] = useState('');
  const [randomCode, setRandomCode] = useState<string>(() => generateRandomRoomCode());
  const [isCustomCodeActive, setIsCustomCodeActive] = useState(false);
  const [customCodeInput, setCustomCodeInput] = useState('');
  const [roomDescription, setRoomDescription] = useState('');
  const [isCreatingRoom, setIsCreatingRoom] = useState(false);

  // Create Character State
  const [targetCampaignCode, setTargetCampaignCode] = useState(currentCampaignCode || (availableCampaigns[0]?.code ?? ''));
  const [charName, setCharName] = useState('');
  const [charTitle, setCharTitle] = useState('Aventureiro');
  const [charClass, setCharClass] = useState('Guerreiro Rúnico');
  const [charRace, setCharRace] = useState('Humano');
  const [originRegion, setOriginRegion] = useState<string>('caeldrin');
  const [primaryLanguage, setPrimaryLanguage] = useState<string>('Caeldrico');
  const [knownLanguages, setKnownLanguages] = useState<string[]>(['Caeldrico', 'Comum']);
  const [selectedAvatar, setSelectedAvatar] = useState(
    'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80'
  );

  // Update language when region changes
  const handleRegionChange = (newRegionId: string) => {
    setOriginRegion(newRegionId);
    const reg = getRegionById(newRegionId);
    if (reg) {
      setPrimaryLanguage(reg.language);
      setKnownLanguages((prev) => {
        const set = new Set([reg.language, 'Comum', ...prev]);
        return Array.from(set);
      });
    }
  };

  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [copiedLink, setCopiedLink] = useState<string | null>(null);

  // Re-roll random room code
  const handleRegenerateRandomCode = () => {
    sound.playCoinClink('PRT');
    const freshCode = generateRandomRoomCode();
    setRandomCode(freshCode);
    setCustomCodeInput('');
    setIsCustomCodeActive(false);
  };

  // Copy code helper
  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    sound.playCoinClink('PRT');
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(null), 2000);
  };

  // Copy direct invite link
  const handleCopyInviteLink = (code: string) => {
    const origin = typeof window !== 'undefined' ? window.location.origin : '';
    const link = `${origin}/?room=${encodeURIComponent(code)}`;
    navigator.clipboard.writeText(link);
    sound.playCoinClink('ORO');
    setCopiedLink(code);
    setTimeout(() => setCopiedLink(null), 2500);
  };

  // Search/Verify room online
  const handleSearchRoom = async (codeToSearch: string) => {
    const clean = normalizeRoomCode(codeToSearch);
    if (!clean) return;

    setIsSearchingOnline(true);
    setJoinError(null);
    setOnlineRoomFound(null);

    const result = await campaignService.checkRoomExists(clean);
    setIsSearchingOnline(false);

    if (result.exists && result.campaign) {
      setOnlineRoomFound(result.campaign);
    } else {
      setJoinError(`Nenhuma sala online encontrada com o código "${clean}". Peça ao Mestre para confirmar o código.`);
    }
  };

  // Join handler
  const handleJoinSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setJoinError(null);
    const code = normalizeRoomCode(joinCode);
    if (!code) return;

    setIsSearchingOnline(true);
    const result = await campaignService.checkRoomExists(code);
    setIsSearchingOnline(false);

    if (!result.exists || !result.campaign) {
      setJoinError(`Nenhuma sala online encontrada com o código "${code}". Verifique o código e tente novamente.`);
      return;
    }

    sound.playSuccessFanfare();
    onSelectCampaign(code);
    if (onCloseLobbyView) onCloseLobbyView();
  };

  // Create Room handler with completely random code
  const handleCreateRoomSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!roomName.trim()) return;

    setIsCreatingRoom(true);
    const finalCode = isCustomCodeActive && customCodeInput.trim()
      ? normalizeRoomCode(customCodeInput)
      : randomCode;

    try {
      const newCamp = await onCreateCampaign(
        roomName.trim(),
        gmName.trim() || 'Mestre do Jogo',
        roomDescription.trim(),
        finalCode
      );

      sound.playSuccessFanfare();
      onSelectCampaign(newCamp.code);
      setRoomName('');
      setGmName('');
      setRoomDescription('');
      setRandomCode(generateRandomRoomCode());
      if (onCloseLobbyView) onCloseLobbyView();
    } finally {
      setIsCreatingRoom(false);
    }
  };

  // Create Character handler
  const handleCreateCharacterSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!charName.trim()) return;

    const codeToUse = targetCampaignCode || currentCampaignCode || availableCampaigns[0]?.code;
    if (!codeToUse) {
      alert('Nenhuma sala online disponível para vincular a ficha.');
      return;
    }

    const regData = getRegionById(originRegion);
    const classData = PLAYABLE_CLASSES.find((c) => c.name.toLowerCase() === charClass.toLowerCase());

    const newChar: CharacterSheet = {
      id: 'char-' + Date.now() + '-' + Math.floor(Math.random() * 1000),
      campaignCode: codeToUse,
      name: charName.trim(),
      title: charTitle.trim(),
      characterClass: charClass.trim(),
      race: charRace.trim(),
      originRegion: originRegion,
      primaryLanguage: primaryLanguage,
      knownLanguages: knownLanguages.length > 0 ? knownLanguages : [primaryLanguage, 'Comum'],
      currentLocation: regData ? `${regData.name} — ${regData.pointsOfInterest[0]?.name || 'Capital'}` : 'Caeldrin — Cidadela Estelar',
      level: 1,
      experience: 0,
      unspentAttributePoints: 3,
      starsLevel: 1,
      avatarUrl: selectedAvatar,
      hp: { current: classData ? 20 + (classData.hitDie === '1d12' ? 12 : classData.hitDie === '1d10' ? 10 : 8) : 25, max: classData ? 20 + (classData.hitDie === '1d12' ? 12 : classData.hitDie === '1d10' ? 10 : 8) : 25 },
      mana: { current: 20, max: 20 },
      stamina: { current: 15, max: 15 },
      armorClass: 14,
      speed: '9m',
      initiative: 2,
      attributes: {
        FOR: 14,
        DES: 14,
        CON: 13,
        INT: 12,
        SAB: 10,
        CAR: 12,
      },
      traits: [
        { label: 'Percepção', value: '+2' },
        { label: 'Atletismo', value: '+3' },
        { label: 'Iniciativa', value: '+2' },
        { label: 'Vigor', value: '+1' },
        { label: 'Vontade', value: '+0' },
        { label: 'Visão', value: 'Normal' },
        ...(regData ? [{ label: `Origem (${regData.name})`, value: regData.culturalTrait }] : []),
      ],
      skillsList: classData ? ['Ataque Básico', `Técnica: ${classData.name}`] : ['Ataque Básico', 'Defesa Rúnica'],
      abilities: [],
      inventory: [
        {
          id: 'inv-' + Date.now(),
          name: 'Espada de Ferro Nobre',
          quantity: 1,
          category: 'arma',
          description: 'Arma inicial de aventureiro.',
          valueAmount: 5,
          valueCurrency: 'BRZ',
        },
      ],
      wallet: {
        BRZ: 50,
        PRT: 10,
        ORO: 2,
        PLN: 0,
        CYB: 0,
      },
      notes: 'Personagem ingressado na mesa online de Nexaria.',
      isMaster: false,
      isOnline: true,
      lastActive: Date.now(),
    };

    onCreateCharacter(codeToUse, newChar);
    sound.playSuccessFanfare();
    setCharName('');
    if (onCloseLobbyView) onCloseLobbyView();
  };

  const AVATARS = [
    'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1563089145-599997674d42?w=500&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
  ];

  return (
    <div className="w-full max-w-4xl mx-auto py-6 px-4">
      {/* Title & Introduction */}
      <div className="relative rounded-2xl border border-amber-600/40 bg-gradient-to-r from-purple-950/80 via-[#0a0714] to-purple-950/80 p-6 sm:p-8 shadow-2xl mb-8 overflow-hidden text-center">
        <div className="absolute top-2 left-2 text-amber-500/40 text-xs font-cinzel select-none">✦</div>
        <div className="absolute top-2 right-2 text-amber-500/40 text-xs font-cinzel select-none">✦</div>
        <div className="absolute bottom-2 left-2 text-amber-500/40 text-xs font-cinzel select-none">✦</div>
        <div className="absolute bottom-2 right-2 text-amber-500/40 text-xs font-cinzel select-none">✦</div>

        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border border-emerald-500/40 bg-emerald-950/40 text-xs font-cinzel text-emerald-300 mb-3 tracking-wider uppercase shadow-inner">
          <Globe2 className="w-3.5 h-3.5 text-emerald-400 animate-pulse" />
          <span>✦ Sistema Online Multijogador em Tempo Real ✦</span>
        </div>

        <h1 className="text-3xl sm:text-5xl font-cinzel font-black tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-amber-100 uppercase drop-shadow-md">
          NEXARIA
        </h1>
        <div className="text-sm sm:text-base font-cinzel font-bold tracking-widest text-purple-300 uppercase mt-1">
          &bull; O LEGADO DO ABISMO &bull;
        </div>

        <p className="text-xs sm:text-sm text-zinc-300 max-w-2xl mx-auto mt-3 font-sans leading-relaxed">
          &ldquo;Em um mundo onde a magia ancestral se choca com a tecnologia avançada, mestres e jogadores se conectam online através de códigos aleatórios seguros para gerenciar fichas, transações de moedas e aventuras em tempo real.&rdquo;
        </p>

        <div className="mt-5 flex flex-wrap items-center justify-center gap-2.5">
          {currentCampaignCode && onCloseLobbyView && (
            <button
              onClick={onCloseLobbyView}
              className="inline-flex items-center gap-2 px-4 py-2 text-xs font-cinzel font-bold text-zinc-950 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 hover:to-amber-400 rounded-xl shadow-lg shadow-amber-950/40 transition"
            >
              Voltar à Mesa Ativa ({currentCampaignCode})
              <ArrowRight className="w-3.5 h-3.5 text-zinc-950" />
            </button>
          )}

          {onOpenTutorial && (
            <button
              onClick={onOpenTutorial}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-cinzel font-semibold text-amber-200 hover:text-white border border-amber-500/40 bg-purple-950/60 hover:bg-purple-900 rounded-xl shadow-md transition"
            >
              <BookOpen className="w-3.5 h-3.5 text-amber-400" />
              <span>Guia do Jogador</span>
            </button>
          )}
        </div>
      </div>

      {/* Official Coins Overview */}
      <div className="mb-8 p-4 rounded-xl border border-purple-900/50 bg-[#0e0a1a]/90 shadow-xl">
        <div className="flex items-center justify-between pb-3 border-b border-purple-900/40 mb-3">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-amber-400 animate-pulse" />
            <span className="text-xs font-cinzel font-bold uppercase tracking-wider text-amber-300">
              Moedas Oficiais do Jogo
            </span>
          </div>
          <span className="text-[10px] font-mono text-purple-300">
            Clique na moeda para virar
          </span>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
          {(['BRZ', 'PRT', 'ORO', 'PLN', 'CYB'] as const).map((curr) => (
            <div
              key={curr}
              className="p-3 rounded-lg border border-zinc-800 bg-zinc-900/60 flex flex-col items-center text-center gap-2 hover:border-amber-500/50 transition"
            >
              <div className="cursor-pointer" title="Clique para virar a moeda">
                <CoinVisual type={curr} size="md" interactiveFlip />
              </div>
              <div>
                <div className="text-xs font-cinzel font-bold text-zinc-200">
                  {curr === 'BRZ' && 'Bronze (BRZ)'}
                  {curr === 'PRT' && 'Prata (PRT)'}
                  {curr === 'ORO' && 'Ouro (ORO)'}
                  {curr === 'PLN' && 'Platina (PLN)'}
                  {curr === 'CYB' && 'Cybermoedas'}
                </div>
                <div className="text-[10px] text-amber-400 font-mono mt-0.5">
                  {curr === 'BRZ' && '1 BRZ'}
                  {curr === 'PRT' && '10 BRZ'}
                  {curr === 'ORO' && '100 BRZ'}
                  {curr === 'PLN' && '1.000 BRZ'}
                  {curr === 'CYB' && '5.000 BRZ'}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 p-1.5 bg-[#120a22]/90 rounded-xl border border-purple-900/60 mb-6">
        <button
          onClick={() => setActiveTab('join')}
          className={`py-2 px-3 rounded-lg text-xs font-cinzel font-semibold flex items-center justify-center gap-2 transition ${
            activeTab === 'join'
              ? 'bg-gradient-to-r from-amber-500 to-amber-600 text-zinc-950 font-bold shadow-md shadow-amber-950/40'
              : 'text-zinc-400 hover:text-amber-200'
          }`}
        >
          <LogIn className="w-4 h-4" />
          Entrar em Sala
        </button>

        <button
          onClick={() => {
            setActiveTab('create_room');
            if (!randomCode) handleRegenerateRandomCode();
          }}
          className={`py-2 px-3 rounded-lg text-xs font-cinzel font-semibold flex items-center justify-center gap-2 transition ${
            activeTab === 'create_room'
              ? 'bg-gradient-to-r from-amber-500 to-amber-600 text-zinc-950 font-bold shadow-md shadow-amber-950/40'
              : 'text-zinc-400 hover:text-amber-200'
          }`}
        >
          <PlusCircle className="w-4 h-4" />
          Criar Sala (Mestre)
        </button>

        <button
          onClick={() => setActiveTab('create_character')}
          className={`py-2 px-3 rounded-lg text-xs font-cinzel font-semibold flex items-center justify-center gap-2 transition ${
            activeTab === 'create_character'
              ? 'bg-gradient-to-r from-amber-500 to-amber-600 text-zinc-950 font-bold shadow-md shadow-amber-950/40'
              : 'text-zinc-400 hover:text-amber-200'
          }`}
        >
          <UserPlus className="w-4 h-4" />
          Nova Ficha
        </button>

        <button
          onClick={() => setActiveTab('manage_rooms')}
          className={`py-2 px-3 rounded-lg text-xs font-cinzel font-semibold flex items-center justify-center gap-2 transition ${
            activeTab === 'manage_rooms'
              ? 'bg-gradient-to-r from-amber-500 to-amber-600 text-zinc-950 font-bold shadow-md shadow-amber-950/40'
              : 'text-zinc-400 hover:text-amber-200'
          }`}
        >
          <KeyRound className="w-4 h-4" />
          Salas Online ({availableCampaigns.length})
        </button>
      </div>

      {/* TAB 1: ENTRAR EM SALA ONLINE */}
      {activeTab === 'join' && (
        <div className="rounded-xl border border-purple-900/60 bg-zinc-900/70 p-6 shadow-xl">
          <div className="flex items-center gap-2 mb-1">
            <Globe2 className="w-5 h-5 text-emerald-400" />
            <h2 className="text-base font-cinzel font-bold text-zinc-100">
              Entrar em uma Sala Online
            </h2>
          </div>
          <p className="text-xs text-zinc-400 mb-5">
            Cole o código aleatório gerado pelo Mestre (ex: <span className="font-mono text-amber-300">7K9M2F</span>) para conectar imediatamente à campanha.
          </p>

          <form onSubmit={handleJoinSubmit} className="space-y-4 max-w-lg">
            <div>
              <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                Código da Sala do Mestre *
              </label>
              <div className="flex gap-2">
                <div className="relative flex-1">
                  <KeyRound className="w-4 h-4 text-amber-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                  <input
                    type="text"
                    required
                    placeholder="Ex: 7K9M2F ou cole o link"
                    value={joinCode}
                    onChange={(e) => {
                      let val = e.target.value;
                      // Handle if user pasted full URL e.g. https://...?room=NX-123
                      if (val.includes('room=')) {
                        const match = val.match(/room=([A-Za-z0-9_-]+)/);
                        if (match) val = match[1];
                      }
                      setJoinCode(val.toUpperCase());
                      setOnlineRoomFound(null);
                      setJoinError(null);
                    }}
                    className="w-full bg-zinc-950 border border-purple-900/60 rounded-lg pl-10 pr-3 py-2.5 text-sm font-mono uppercase tracking-widest text-amber-300 placeholder:text-zinc-600 focus:outline-none focus:border-amber-500"
                  />
                </div>
                <button
                  type="button"
                  onClick={() => handleSearchRoom(joinCode)}
                  disabled={!joinCode.trim() || isSearchingOnline}
                  className="px-3 py-2.5 bg-purple-950 hover:bg-purple-900 border border-purple-800 text-purple-200 text-xs font-medium rounded-lg transition flex items-center gap-1.5 disabled:opacity-50"
                  title="Buscar Sala Online"
                >
                  {isSearchingOnline ? (
                    <Loader2 className="w-4 h-4 animate-spin text-amber-400" />
                  ) : (
                    <Search className="w-4 h-4 text-amber-400" />
                  )}
                  <span className="hidden sm:inline">Verificar</span>
                </button>
              </div>
            </div>

            {/* Online room preview card if verified */}
            {onlineRoomFound && (
              <div className="p-4 rounded-xl border border-emerald-500/50 bg-emerald-950/20 flex flex-col gap-2 transition animate-fadeIn">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span className="text-xs font-cinzel font-bold text-emerald-200">
                      Sala Encontrada no Servidor!
                    </span>
                  </div>
                  <span className="px-2 py-0.5 rounded bg-zinc-900 text-amber-300 font-mono text-xs font-bold border border-amber-500/30">
                    {onlineRoomFound.code}
                  </span>
                </div>
                <div className="text-sm font-bold text-zinc-100">
                  {onlineRoomFound.name}
                </div>
                <div className="text-xs text-zinc-400 flex items-center gap-3">
                  <span>Mestre: <strong className="text-zinc-200">{onlineRoomFound.gmName}</strong></span>
                  <span>•</span>
                  <span>{onlineRoomFound.players.length} Fichas de Jogadores</span>
                </div>
              </div>
            )}

            {joinError && (
              <div className="p-3 rounded-lg bg-red-950/40 border border-red-900/60 text-xs text-red-300">
                {joinError}
              </div>
            )}

            <button
              type="submit"
              disabled={isSearchingOnline}
              className="w-full py-2.5 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 hover:to-amber-400 text-zinc-950 font-bold text-xs font-cinzel tracking-wider rounded-lg shadow-md transition flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {isSearchingOnline ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin text-zinc-950" />
                  Conectando à Sala Online...
                </>
              ) : (
                <>
                  <LogIn className="w-4 h-4 text-zinc-950" />
                  Ingressar na Sala Online
                </>
              )}
            </button>
          </form>

          {/* Quick list of available rooms */}
          {availableCampaigns.length > 0 && (
            <div className="mt-8 pt-6 border-t border-purple-900/40">
              <span className="text-xs font-cinzel font-semibold text-zinc-300 block mb-3">
                ✦ Mesas Online Ativas no Servidor:
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {availableCampaigns.map((camp) => (
                  <div
                    key={camp.code}
                    onClick={() => {
                      onSelectCampaign(camp.code);
                      if (onCloseLobbyView) onCloseLobbyView();
                    }}
                    className={`p-3 rounded-lg border cursor-pointer flex items-center justify-between transition ${
                      camp.code === currentCampaignCode
                        ? 'border-amber-500/60 bg-purple-950/40 shadow-md shadow-amber-950/20'
                        : 'border-zinc-800 bg-zinc-950/60 hover:border-purple-800'
                    }`}
                  >
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-semibold text-xs text-zinc-200">
                          {camp.name}
                        </span>
                        <span className="px-1.5 py-0.5 rounded bg-zinc-800 text-amber-300 font-mono text-[10px] font-bold">
                          {camp.code}
                        </span>
                      </div>
                      <span className="text-[11px] text-zinc-400">
                        Mestre: {camp.gmName} • {camp.players.length} Fichas
                      </span>
                    </div>

                    {camp.code === currentCampaignCode ? (
                      <span className="text-[11px] text-emerald-400 font-medium flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Atual
                      </span>
                    ) : (
                      <span className="text-xs text-amber-400 font-bold hover:text-amber-300">
                        Entrar ➔
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* TAB 2: CRIAR SALA (COM CÓDIGO COMPLETAMENTE ALEATÓRIO) */}
      {activeTab === 'create_room' && (
        <div className="rounded-xl border border-purple-900/60 bg-zinc-900/70 p-6 shadow-xl">
          <div className="flex items-center gap-2 mb-1">
            <PlusCircle className="w-5 h-5 text-amber-400" />
            <h2 className="text-base font-cinzel font-bold text-zinc-100">
              Criar Nova Sala Online (Painel do Mestre)
            </h2>
          </div>
          <p className="text-xs text-zinc-400 mb-5">
            O sistema gera automaticamente um <strong>código completamente aleatório e seguro</strong> para que seus jogadores possam se conectar online de qualquer lugar.
          </p>

          <form onSubmit={handleCreateRoomSubmit} className="space-y-4 max-w-lg">
            {/* Caixa em destaque do Código de Sala Aleatório */}
            <div className="p-4 rounded-xl border border-amber-500/40 bg-gradient-to-r from-amber-950/30 via-purple-950/40 to-zinc-950 shadow-inner">
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-cinzel font-bold text-amber-300 uppercase tracking-wider flex items-center gap-1.5">
                  <Dice5 className="w-4 h-4 text-amber-400" />
                  Código de Sala Aleatório Gerado:
                </label>
                <button
                  type="button"
                  onClick={handleRegenerateRandomCode}
                  className="px-2.5 py-1 text-[11px] font-cinzel font-bold text-amber-300 hover:text-amber-100 bg-amber-950/60 hover:bg-amber-900/80 border border-amber-500/50 rounded-lg flex items-center gap-1 transition shadow-sm"
                  title="Gerar outro código aleatório"
                >
                  <RotateCcw className="w-3 h-3 text-amber-400" />
                  Sortear Novo Código
                </button>
              </div>

              {!isCustomCodeActive ? (
                <div className="flex items-center justify-between bg-zinc-950/90 border border-amber-500/50 rounded-lg px-4 py-2.5">
                  <span className="text-lg sm:text-xl font-mono font-black text-amber-300 tracking-widest">
                    {randomCode}
                  </span>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => handleCopyCode(randomCode)}
                      className="px-2 py-1 text-xs font-medium text-amber-300 hover:text-white bg-zinc-900 border border-zinc-700 rounded-md transition flex items-center gap-1"
                      title="Copiar código"
                    >
                      {copiedCode === randomCode ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                          <span className="text-emerald-400">Copiado!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5" />
                          <span>Copiar</span>
                        </>
                      )}
                    </button>
                    <button
                      type="button"
                      onClick={() => setIsCustomCodeActive(true)}
                      className="text-[11px] text-zinc-400 hover:text-amber-200 underline"
                    >
                      Personalizar
                    </button>
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="flex gap-2">
                    <input
                      type="text"
                      placeholder="Digite o código customizado"
                      value={customCodeInput}
                      onChange={(e) => setCustomCodeInput(e.target.value.toUpperCase())}
                      className="flex-1 bg-zinc-950 border border-zinc-700 rounded-lg px-3 py-2 text-sm font-mono uppercase text-amber-300 focus:outline-none focus:border-amber-500"
                    />
                    <button
                      type="button"
                      onClick={() => {
                        setIsCustomCodeActive(false);
                        setCustomCodeInput('');
                      }}
                      className="px-3 py-2 text-xs text-zinc-400 hover:text-zinc-200 bg-zinc-900 border border-zinc-800 rounded-lg"
                    >
                      Usar Aleatório
                    </button>
                  </div>
                </div>
              )}

              <p className="text-[11px] text-zinc-400 mt-2">
                Compartilhe esse código com seus jogadores para eles entrarem na sua mesa online.
              </p>
            </div>

            <div>
              <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                Nome da Sala / Campanha *
              </label>
              <input
                type="text"
                required
                placeholder="Ex: Nexaria — O Legado do Abismo: Capítulo I"
                value={roomName}
                onChange={(e) => setRoomName(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3.5 py-2 text-xs text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                Nome do Mestre (GM)
              </label>
              <input
                type="text"
                placeholder="Ex: Mestre Vaelor"
                value={gmName}
                onChange={(e) => setGmName(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3.5 py-2 text-xs text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                Sinopse / Regras da Mesa
              </label>
              <textarea
                rows={3}
                placeholder="Contexto da campanha, diretrizes monetárias e avisos para os aventureiros..."
                value={roomDescription}
                onChange={(e) => setRoomDescription(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3.5 py-2 text-xs text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-amber-500"
              />
            </div>

            <button
              type="submit"
              disabled={isCreatingRoom}
              className="w-full py-2.5 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 hover:to-amber-400 text-zinc-950 font-bold text-xs font-cinzel tracking-wider rounded-lg shadow-md transition flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {isCreatingRoom ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin text-zinc-950" />
                  Criando Sala Online...
                </>
              ) : (
                <>
                  <PlusCircle className="w-4 h-4 text-zinc-950" />
                  Criar Sala Online e Iniciar Campanha
                </>
              )}
            </button>
          </form>
        </div>
      )}

      {/* TAB 3: NOVA FICHA DE PERSONAGEM */}
      {activeTab === 'create_character' && (
        <div className="rounded-xl border border-purple-900/60 bg-zinc-900/70 p-6 shadow-xl">
          <div className="flex items-center gap-2 mb-1">
            <UserPlus className="w-5 h-5 text-amber-400" />
            <h2 className="text-base font-cinzel font-bold text-zinc-100">
              Forjar Ficha de Personagem Online
            </h2>
          </div>
          <p className="text-xs text-zinc-400 mb-5">
            Crie a sua ficha para a mesa online. Ela será sincronizada automaticamente com o painel do Mestre.
          </p>

          <form onSubmit={handleCreateCharacterSubmit} className="space-y-4 max-w-lg">
            <div>
              <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                Vincular à Sala Online *
              </label>
              <select
                value={targetCampaignCode}
                onChange={(e) => setTargetCampaignCode(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-500 cursor-pointer"
              >
                {availableCampaigns.map((camp) => (
                  <option key={camp.code} value={camp.code}>
                    {camp.name} ({camp.code}) — Mestre: {camp.gmName}
                  </option>
                ))}
              </select>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                  Nome do Personagem *
                </label>
                <input
                  type="text"
                  required
                  placeholder="Ex: Alistair"
                  value={charName}
                  onChange={(e) => setCharName(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3.5 py-2 text-xs text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-amber-500"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                  Título / Arquétipo
                </label>
                <input
                  type="text"
                  placeholder="Ex: Caçador das Terras Ermas"
                  value={charTitle}
                  onChange={(e) => setCharTitle(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3.5 py-2 text-xs text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-amber-500"
                />
              </div>
            </div>

            {/* Seleção de Classe e Raça */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-zinc-300 mb-1.5 flex items-center justify-between">
                  <span>Classe ({PLAYABLE_CLASSES.length} disponíveis)</span>
                  <span className="text-[10px] text-amber-400 font-mono">Oficial Nexaria</span>
                </label>
                <select
                  value={charClass}
                  onChange={(e) => setCharClass(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-500"
                >
                  {['Marcial & Tanque', 'Conjurador Arcano', 'Divino & Espiritual', 'Especialista & Furtivo', 'Cibernético & Tecnomágico'].map((cat) => (
                    <optgroup key={cat} label={`── ${cat} ──`} className="bg-zinc-900 text-zinc-300 font-semibold">
                      {PLAYABLE_CLASSES.filter((c) => c.category === cat).map((cls) => (
                        <option key={cls.id} value={cls.name} className="bg-zinc-950 text-zinc-100 font-normal">
                          {cls.icon} {cls.name} ({cls.primaryAttribute})
                        </option>
                      ))}
                    </optgroup>
                  ))}
                </select>

                {/* Card de Informações da Classe Selecionada */}
                {(() => {
                  const selClass = PLAYABLE_CLASSES.find((c) => c.name.toLowerCase() === charClass.toLowerCase());
                  if (!selClass) return null;
                  return (
                    <div className="mt-2 p-2 rounded-lg bg-zinc-950/80 border border-amber-500/20 text-[11px] space-y-1">
                      <div className="flex items-center justify-between text-amber-400 font-semibold">
                        <span>{selClass.icon} {selClass.name} • {selClass.category}</span>
                        <span className="text-[10px] px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-300 font-mono">
                          {selClass.hitDie} • Atrib: {selClass.primaryAttribute}
                        </span>
                      </div>
                      <p className="text-zinc-300 text-[10px] leading-relaxed">{selClass.description}</p>
                      <div className="text-[9px] text-zinc-400">
                        <strong className="text-zinc-300">Característica:</strong> {selClass.keyFeature} | <strong className="text-zinc-300">Perícias:</strong> {selClass.startingSkills.join(', ')}
                      </div>
                    </div>
                  );
                })()}
              </div>

              <div>
                <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                  Raça ({PLAYABLE_RACES.length} opções disponíveis)
                </label>
                <select
                  value={charRace}
                  onChange={(e) => setCharRace(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-500"
                >
                  {['Comum', 'Élfica', 'Anã & Pequena', 'Planar & Abissal', 'Tecnológica & Fera'].map((category) => (
                    <optgroup key={category} label={`── ${category} ──`} className="bg-zinc-900 text-zinc-300 font-semibold">
                      {PLAYABLE_RACES.filter((r) => r.category === category).map((race) => (
                        <option key={race.id} value={race.name} className="bg-zinc-950 text-zinc-100 font-normal">
                          {race.name}
                        </option>
                      ))}
                    </optgroup>
                  ))}
                </select>

                {/* Card de Traço e Descrição da Raça Selecionada */}
                {(() => {
                  const selected = PLAYABLE_RACES.find((r) => r.name === charRace);
                  if (!selected) return null;
                  return (
                    <div className="mt-2 p-2 rounded-lg bg-zinc-950/80 border border-amber-500/20 text-[11px] space-y-0.5">
                      <div className="text-amber-400 font-semibold flex items-center justify-between">
                        <span>Traços Raciais:</span>
                        <span className="text-[10px] text-zinc-400 font-mono">{selected.category}</span>
                      </div>
                      <p className="text-zinc-200">{selected.traits}</p>
                      <p className="text-zinc-400 italic text-[10px]">{selected.description}</p>
                    </div>
                  );
                })()}
              </div>
            </div>

            {/* SEÇÃO REGIONAL: Região de Origem dos Reinos de Eldria & Idioma Nativo */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 p-3 rounded-xl border border-purple-900/50 bg-gradient-to-br from-purple-950/30 via-zinc-950 to-zinc-950">
              <div>
                <label className="block text-xs font-medium text-amber-200 mb-1.5 flex items-center gap-1.5">
                  <Globe2 className="w-3.5 h-3.5 text-amber-400" />
                  <span>Região de Origem (Eldria)</span>
                </label>
                <select
                  value={originRegion}
                  onChange={(e) => handleRegionChange(e.target.value)}
                  className="w-full bg-zinc-950 border border-purple-800/60 rounded-lg px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-400"
                >
                  {ORIGIN_REGIONS.map((reg) => (
                    <option key={reg.id} value={reg.id} className="bg-zinc-950 text-zinc-100">
                      {reg.symbol} {reg.name} ({reg.subtitle})
                    </option>
                  ))}
                </select>

                {/* Card da Região Selecionada */}
                {(() => {
                  const selReg = getRegionById(originRegion);
                  if (!selReg) return null;
                  return (
                    <div className="mt-2 p-2 rounded-lg bg-zinc-900/90 border border-purple-800/40 text-[11px] space-y-1">
                      <div className="flex items-center justify-between text-purple-300 font-medium">
                        <span>{selReg.symbol} {selReg.name}</span>
                        <span className="text-[10px] text-amber-400 font-semibold">{selReg.bonusAttribute}</span>
                      </div>
                      <p className="text-zinc-300 text-[10px] italic leading-tight">
                        "{selReg.culturalTrait}"
                      </p>
                      <div className="text-[9px] text-zinc-400 flex items-center gap-1 pt-0.5">
                        <span className="text-amber-400/90 font-mono">Runas:</span> {selReg.runicAlphabetName}
                      </div>
                    </div>
                  );
                })()}
              </div>

              <div>
                <label className="block text-xs font-medium text-amber-200 mb-1.5 flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                  <span>Idioma Materno &amp; Conhecido</span>
                </label>
                <div className="space-y-2">
                  <div className="relative">
                    <input
                      type="text"
                      value={primaryLanguage}
                      onChange={(e) => setPrimaryLanguage(e.target.value)}
                      placeholder="Idioma Nativo..."
                      className="w-full bg-zinc-950 border border-purple-800/60 rounded-lg px-3 py-2 text-xs text-amber-200 font-medium focus:outline-none focus:border-amber-400"
                    />
                    <span className="absolute right-2.5 top-2 text-[10px] text-zinc-500 uppercase tracking-wider font-mono">
                      Nativo
                    </span>
                  </div>

                  <div className="p-2 rounded-lg bg-zinc-900/90 border border-zinc-800 text-[11px] space-y-1">
                    <span className="text-[10px] text-zinc-400 block font-medium">
                      Línguas Faladas pelo Aventureiro:
                    </span>
                    <div className="flex flex-wrap gap-1">
                      {knownLanguages.map((lang, idx) => (
                        <span
                          key={idx}
                          className="px-2 py-0.5 rounded bg-amber-500/10 border border-amber-500/30 text-amber-300 text-[10px] font-medium flex items-center gap-1"
                        >
                          ✦ {lang}
                        </span>
                      ))}
                    </div>
                    <p className="text-[9px] text-zinc-400 mt-1">
                      O idioma materno é definido pelas terras natais do personagem em Eldria e utilizado para decifrar inscrições arcanas e runas antigas.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Retrato */}
            <div>
              <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                Retrato do Personagem
              </label>
              <div className="flex items-center gap-2">
                {AVATARS.map((url, i) => (
                  <img
                    key={i}
                    src={url}
                    alt="Preset"
                    onClick={() => setSelectedAvatar(url)}
                    className={`w-11 h-11 rounded-lg object-cover cursor-pointer border transition ${
                      selectedAvatar === url
                        ? 'border-amber-400 scale-105'
                        : 'border-zinc-800 opacity-60 hover:opacity-100'
                    }`}
                  />
                ))}
              </div>
            </div>

            <div className="p-3 rounded-lg bg-zinc-950 border border-purple-900/40 text-[11px] text-zinc-400 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-amber-400 shrink-0" />
              <span>
                Bolsa Inicial Oficial: <strong className="text-amber-300">50 Bronze, 10 Prata e 2 Ouro</strong> pronta para trocas e compras.
              </span>
            </div>

            <button
              type="submit"
              className="w-full py-2.5 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 hover:to-amber-400 text-zinc-950 font-bold text-xs font-cinzel tracking-wider rounded-lg shadow-md transition flex items-center justify-center gap-2"
            >
              <UserPlus className="w-4 h-4 text-zinc-950" />
              Salvar Ficha Online e Ingressar na Sala
            </button>
          </form>
        </div>
      )}

      {/* TAB 4: GERENCIAR SALAS ONLINE */}
      {activeTab === 'manage_rooms' && (
        <div className="rounded-xl border border-purple-900/60 bg-zinc-900/70 p-6 shadow-xl">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5">
            <div>
              <div className="flex items-center gap-2">
                <Globe2 className="w-4 h-4 text-emerald-400" />
                <h2 className="text-base font-cinzel font-bold text-zinc-100">
                  Salas Online Ativas no Servidor
                </h2>
              </div>
              <p className="text-xs text-zinc-400">
                Copie códigos aleatórios, links diretos de convite ou ingresse em qualquer sala.
              </p>
            </div>
            <button
              onClick={() => setActiveTab('create_room')}
              className="px-3 py-1.5 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 text-zinc-950 font-cinzel font-bold text-xs rounded-lg transition self-start sm:self-auto flex items-center gap-1.5 shadow-sm"
            >
              <PlusCircle className="w-3.5 h-3.5 text-zinc-950" />
              Nova Sala
            </button>
          </div>

          <div className="space-y-3">
            {availableCampaigns.length === 0 ? (
              <div className="text-center py-10 text-xs text-zinc-500">
                Nenhuma sala encontrada no servidor.
              </div>
            ) : (
              availableCampaigns.map((camp) => (
                <div
                  key={camp.code}
                  className="p-4 rounded-xl border border-zinc-800 bg-zinc-950/70 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 hover:border-purple-800 transition"
                >
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <h3 className="text-sm font-semibold text-zinc-200">
                        {camp.name}
                      </h3>
                      {camp.code === currentCampaignCode && (
                        <span className="px-1.5 py-0.5 rounded bg-emerald-950 text-emerald-300 border border-emerald-800 text-[10px] font-medium">
                          Mesa Ativa
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 text-xs text-zinc-400">
                      <span>Mestre: <strong className="text-zinc-300">{camp.gmName}</strong></span>
                      <span>•</span>
                      <span>{camp.players.length} Personagens</span>
                      <span>•</span>
                      <span>{camp.transactions.length} Transações</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 self-end sm:self-auto flex-wrap">
                    {/* Copy Room Code */}
                    <button
                      onClick={() => handleCopyCode(camp.code)}
                      className="px-2.5 py-1.5 rounded-md border border-zinc-800 bg-zinc-900 hover:bg-zinc-800 text-amber-300 text-xs font-mono font-bold flex items-center gap-1.5 transition"
                      title="Copiar código de sala"
                    >
                      {copiedCode === camp.code ? (
                        <>
                          <Check className="w-3 h-3 text-emerald-400" />
                          <span className="text-emerald-400">Copiado!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3 h-3 text-zinc-400" />
                          <span>{camp.code}</span>
                        </>
                      )}
                    </button>

                    {/* Copy Direct Invite Link */}
                    <button
                      onClick={() => handleCopyInviteLink(camp.code)}
                      className="px-2.5 py-1.5 rounded-md border border-purple-900/70 bg-purple-950/50 hover:bg-purple-900/60 text-purple-200 text-xs flex items-center gap-1.5 transition"
                      title="Copiar Link de Convite Direto para Jogadores"
                    >
                      {copiedLink === camp.code ? (
                        <>
                          <Check className="w-3 h-3 text-emerald-400" />
                          <span className="text-emerald-300 text-[11px]">Link Copiado!</span>
                        </>
                      ) : (
                        <>
                          <Share2 className="w-3 h-3 text-purple-300" />
                          <span className="text-[11px] hidden sm:inline">Link de Convite</span>
                        </>
                      )}
                    </button>

                    {/* Enter Room */}
                    <button
                      onClick={() => {
                        onSelectCampaign(camp.code);
                        if (onCloseLobbyView) onCloseLobbyView();
                      }}
                      className="px-3 py-1.5 bg-zinc-100 hover:bg-white text-zinc-950 text-xs font-medium rounded-md transition"
                    >
                      Entrar
                    </button>

                    {/* Delete Room */}
                    <button
                      onClick={() => {
                        if (confirm(`Tem certeza que deseja excluir a sala "${camp.name}" (${camp.code})? Esta ação não pode ser desfeita.`)) {
                          onDeleteCampaign(camp.code);
                        }
                      }}
                      className="p-1.5 rounded-md border border-zinc-800 bg-zinc-900 hover:bg-red-950/40 hover:border-red-800 text-zinc-400 hover:text-red-300 transition"
                      title="Excluir Sala"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Reset site section */}
          <div className="mt-8 pt-6 border-t border-zinc-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs">
            <div>
              <span className="font-semibold text-zinc-300 block">
                Zerar Cache Local do Navegador
              </span>
              <span className="text-zinc-500">
                Redefine os dados locais salvos em cache no seu dispositivo.
              </span>
            </div>
            <button
              onClick={() => {
                if (confirm('Deseja realmente zerar o cache local do navegador?')) {
                  onResetAllData();
                }
              }}
              className="px-3 py-1.5 rounded-md border border-zinc-800 bg-zinc-950 hover:bg-red-950/50 hover:border-red-900 text-zinc-400 hover:text-red-300 text-xs font-medium flex items-center gap-1.5 transition shrink-0"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              Zerar Cache
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
